#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartEDU_2.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SmartEdu1")]
	public partial class LinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertTHUCDON(THUCDON instance);
    partial void UpdateTHUCDON(THUCDON instance);
    partial void DeleteTHUCDON(THUCDON instance);
    partial void InsertDANHGIA(DANHGIA instance);
    partial void UpdateDANHGIA(DANHGIA instance);
    partial void DeleteDANHGIA(DANHGIA instance);
    partial void InsertGIAOVIEN(GIAOVIEN instance);
    partial void UpdateGIAOVIEN(GIAOVIEN instance);
    partial void DeleteGIAOVIEN(GIAOVIEN instance);
    partial void InsertHOCSINH(HOCSINH instance);
    partial void UpdateHOCSINH(HOCSINH instance);
    partial void DeleteHOCSINH(HOCSINH instance);
    partial void InsertKHOAHOC(KHOAHOC instance);
    partial void UpdateKHOAHOC(KHOAHOC instance);
    partial void DeleteKHOAHOC(KHOAHOC instance);
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertPHIEUDANGKYHOC(PHIEUDANGKYHOC instance);
    partial void UpdatePHIEUDANGKYHOC(PHIEUDANGKYHOC instance);
    partial void DeletePHIEUDANGKYHOC(PHIEUDANGKYHOC instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHONGBAO(THONGBAO instance);
    partial void UpdateTHONGBAO(THONGBAO instance);
    partial void DeleteTHONGBAO(THONGBAO instance);
    partial void InsertTHONGTINHOATDONG(THONGTINHOATDONG instance);
    partial void UpdateTHONGTINHOATDONG(THONGTINHOATDONG instance);
    partial void DeleteTHONGTINHOATDONG(THONGTINHOATDONG instance);
    #endregion
		
		public LinQDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SmartEdu1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<THUCDON> THUCDONs
		{
			get
			{
				return this.GetTable<THUCDON>();
			}
		}
		
		public System.Data.Linq.Table<DANHGIA> DANHGIAs
		{
			get
			{
				return this.GetTable<DANHGIA>();
			}
		}
		
		public System.Data.Linq.Table<DANHSACHDANGKYHOATDONG> DANHSACHDANGKYHOATDONGs
		{
			get
			{
				return this.GetTable<DANHSACHDANGKYHOATDONG>();
			}
		}
		
		public System.Data.Linq.Table<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this.GetTable<GIAOVIEN>();
			}
		}
		
		public System.Data.Linq.Table<HOCSINH> HOCSINHs
		{
			get
			{
				return this.GetTable<HOCSINH>();
			}
		}
		
		public System.Data.Linq.Table<KHOAHOC> KHOAHOCs
		{
			get
			{
				return this.GetTable<KHOAHOC>();
			}
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDANGKYHOC> PHIEUDANGKYHOCs
		{
			get
			{
				return this.GetTable<PHIEUDANGKYHOC>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THONGBAO> THONGBAOs
		{
			get
			{
				return this.GetTable<THONGBAO>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINHOATDONG> THONGTINHOATDONGs
		{
			get
			{
				return this.GetTable<THONGTINHOATDONG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoanAdmin;
		
		private string _MatKhauAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanAdminChanging(string value);
    partial void OnTaiKhoanAdminChanged();
    partial void OnMatKhauAdminChanging(string value);
    partial void OnMatKhauAdminChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanAdmin", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoanAdmin
		{
			get
			{
				return this._TaiKhoanAdmin;
			}
			set
			{
				if ((this._TaiKhoanAdmin != value))
				{
					this.OnTaiKhoanAdminChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanAdmin = value;
					this.SendPropertyChanged("TaiKhoanAdmin");
					this.OnTaiKhoanAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauAdmin", DbType="NVarChar(50)")]
		public string MatKhauAdmin
		{
			get
			{
				return this._MatKhauAdmin;
			}
			set
			{
				if ((this._MatKhauAdmin != value))
				{
					this.OnMatKhauAdminChanging(value);
					this.SendPropertyChanging();
					this._MatKhauAdmin = value;
					this.SendPropertyChanged("MatKhauAdmin");
					this.OnMatKhauAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUCDON")]
	public partial class THUCDON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATHUCDON;
		
		private System.Nullable<int> _THU;
		
		private string _BUOISANG;
		
		private string _BUOITRUA;
		
		private string _BUOIPHU;
		
		private string _TRANGMIENG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCDONChanging(int value);
    partial void OnMATHUCDONChanged();
    partial void OnTHUChanging(System.Nullable<int> value);
    partial void OnTHUChanged();
    partial void OnBUOISANGChanging(string value);
    partial void OnBUOISANGChanged();
    partial void OnBUOITRUAChanging(string value);
    partial void OnBUOITRUAChanged();
    partial void OnBUOIPHUChanging(string value);
    partial void OnBUOIPHUChanged();
    partial void OnTRANGMIENGChanging(string value);
    partial void OnTRANGMIENGChanged();
    #endregion
		
		public THUCDON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCDON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATHUCDON
		{
			get
			{
				return this._MATHUCDON;
			}
			set
			{
				if ((this._MATHUCDON != value))
				{
					this.OnMATHUCDONChanging(value);
					this.SendPropertyChanging();
					this._MATHUCDON = value;
					this.SendPropertyChanged("MATHUCDON");
					this.OnMATHUCDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THU", DbType="Int")]
		public System.Nullable<int> THU
		{
			get
			{
				return this._THU;
			}
			set
			{
				if ((this._THU != value))
				{
					this.OnTHUChanging(value);
					this.SendPropertyChanging();
					this._THU = value;
					this.SendPropertyChanged("THU");
					this.OnTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUOISANG", DbType="NVarChar(50)")]
		public string BUOISANG
		{
			get
			{
				return this._BUOISANG;
			}
			set
			{
				if ((this._BUOISANG != value))
				{
					this.OnBUOISANGChanging(value);
					this.SendPropertyChanging();
					this._BUOISANG = value;
					this.SendPropertyChanged("BUOISANG");
					this.OnBUOISANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUOITRUA", DbType="NVarChar(50)")]
		public string BUOITRUA
		{
			get
			{
				return this._BUOITRUA;
			}
			set
			{
				if ((this._BUOITRUA != value))
				{
					this.OnBUOITRUAChanging(value);
					this.SendPropertyChanging();
					this._BUOITRUA = value;
					this.SendPropertyChanged("BUOITRUA");
					this.OnBUOITRUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUOIPHU", DbType="NVarChar(50)")]
		public string BUOIPHU
		{
			get
			{
				return this._BUOIPHU;
			}
			set
			{
				if ((this._BUOIPHU != value))
				{
					this.OnBUOIPHUChanging(value);
					this.SendPropertyChanging();
					this._BUOIPHU = value;
					this.SendPropertyChanged("BUOIPHU");
					this.OnBUOIPHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGMIENG", DbType="NVarChar(50)")]
		public string TRANGMIENG
		{
			get
			{
				return this._TRANGMIENG;
			}
			set
			{
				if ((this._TRANGMIENG != value))
				{
					this.OnTRANGMIENGChanging(value);
					this.SendPropertyChanging();
					this._TRANGMIENG = value;
					this.SendPropertyChanged("TRANGMIENG");
					this.OnTRANGMIENGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHGIA")]
	public partial class DANHGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADG;
		
		private string _HOCTAP;
		
		private string _DAODUC;
		
		private string _THETHAO;
		
		private string _HOATDONG;
		
		private System.Nullable<int> _THANG;
		
		private System.Nullable<int> _MAHS;
		
		private System.Nullable<int> _NAM;
		
		private EntityRef<HOCSINH> _HOCSINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADGChanging(int value);
    partial void OnMADGChanged();
    partial void OnHOCTAPChanging(string value);
    partial void OnHOCTAPChanged();
    partial void OnDAODUCChanging(string value);
    partial void OnDAODUCChanged();
    partial void OnTHETHAOChanging(string value);
    partial void OnTHETHAOChanged();
    partial void OnHOATDONGChanging(string value);
    partial void OnHOATDONGChanged();
    partial void OnTHANGChanging(System.Nullable<int> value);
    partial void OnTHANGChanged();
    partial void OnMAHSChanging(System.Nullable<int> value);
    partial void OnMAHSChanged();
    partial void OnNAMChanging(System.Nullable<int> value);
    partial void OnNAMChanged();
    #endregion
		
		public DANHGIA()
		{
			this._HOCSINH = default(EntityRef<HOCSINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADG
		{
			get
			{
				return this._MADG;
			}
			set
			{
				if ((this._MADG != value))
				{
					this.OnMADGChanging(value);
					this.SendPropertyChanging();
					this._MADG = value;
					this.SendPropertyChanged("MADG");
					this.OnMADGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCTAP", DbType="NVarChar(8)")]
		public string HOCTAP
		{
			get
			{
				return this._HOCTAP;
			}
			set
			{
				if ((this._HOCTAP != value))
				{
					this.OnHOCTAPChanging(value);
					this.SendPropertyChanging();
					this._HOCTAP = value;
					this.SendPropertyChanged("HOCTAP");
					this.OnHOCTAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DAODUC", DbType="NVarChar(8)")]
		public string DAODUC
		{
			get
			{
				return this._DAODUC;
			}
			set
			{
				if ((this._DAODUC != value))
				{
					this.OnDAODUCChanging(value);
					this.SendPropertyChanging();
					this._DAODUC = value;
					this.SendPropertyChanged("DAODUC");
					this.OnDAODUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THETHAO", DbType="NVarChar(8)")]
		public string THETHAO
		{
			get
			{
				return this._THETHAO;
			}
			set
			{
				if ((this._THETHAO != value))
				{
					this.OnTHETHAOChanging(value);
					this.SendPropertyChanging();
					this._THETHAO = value;
					this.SendPropertyChanged("THETHAO");
					this.OnTHETHAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOATDONG", DbType="NVarChar(8)")]
		public string HOATDONG
		{
			get
			{
				return this._HOATDONG;
			}
			set
			{
				if ((this._HOATDONG != value))
				{
					this.OnHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._HOATDONG = value;
					this.SendPropertyChanged("HOATDONG");
					this.OnHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANG", DbType="Int")]
		public System.Nullable<int> THANG
		{
			get
			{
				return this._THANG;
			}
			set
			{
				if ((this._THANG != value))
				{
					this.OnTHANGChanging(value);
					this.SendPropertyChanging();
					this._THANG = value;
					this.SendPropertyChanged("THANG");
					this.OnTHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int")]
		public System.Nullable<int> MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					if (this._HOCSINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Int")]
		public System.Nullable<int> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this.OnNAMChanging(value);
					this.SendPropertyChanging();
					this._NAM = value;
					this.SendPropertyChanged("NAM");
					this.OnNAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_DANHGIA", Storage="_HOCSINH", ThisKey="MAHS", OtherKey="MAHS", IsForeignKey=true)]
		public HOCSINH HOCSINH
		{
			get
			{
				return this._HOCSINH.Entity;
			}
			set
			{
				HOCSINH previousValue = this._HOCSINH.Entity;
				if (((previousValue != value) 
							|| (this._HOCSINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOCSINH.Entity = null;
						previousValue.DANHGIAs.Remove(this);
					}
					this._HOCSINH.Entity = value;
					if ((value != null))
					{
						value.DANHGIAs.Add(this);
						this._MAHS = value.MAHS;
					}
					else
					{
						this._MAHS = default(Nullable<int>);
					}
					this.SendPropertyChanged("HOCSINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHSACHDANGKYHOATDONG")]
	public partial class DANHSACHDANGKYHOATDONG
	{
		
		private System.Nullable<int> _STT;
		
		private string _TENHS;
		
		private System.Nullable<int> _MALOP;
		
		private System.Nullable<int> _MAHOATDONG;
		
		private string _PHITHAMGIA;
		
		private System.Nullable<int> _MAHS;
		
		public DANHSACHDANGKYHOATDONG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHS", DbType="NVarChar(50)")]
		public string TENHS
		{
			get
			{
				return this._TENHS;
			}
			set
			{
				if ((this._TENHS != value))
				{
					this._TENHS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Int")]
		public System.Nullable<int> MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this._MALOP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOATDONG", DbType="Int")]
		public System.Nullable<int> MAHOATDONG
		{
			get
			{
				return this._MAHOATDONG;
			}
			set
			{
				if ((this._MAHOATDONG != value))
				{
					this._MAHOATDONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHITHAMGIA", DbType="NChar(10)")]
		public string PHITHAMGIA
		{
			get
			{
				return this._PHITHAMGIA;
			}
			set
			{
				if ((this._PHITHAMGIA != value))
				{
					this._PHITHAMGIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", DbType="Int")]
		public System.Nullable<int> MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this._MAHS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIAOVIEN")]
	public partial class GIAOVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAGV;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private System.Nullable<int> _MALOP;
		
		private EntityRef<LOP> _LOP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAGVChanging(int value);
    partial void OnMAGVChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMALOPChanging(System.Nullable<int> value);
    partial void OnMALOPChanged();
    #endregion
		
		public GIAOVIEN()
		{
			this._LOP = default(EntityRef<LOP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAGV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAGV
		{
			get
			{
				return this._MAGV;
			}
			set
			{
				if ((this._MAGV != value))
				{
					this.OnMAGVChanging(value);
					this.SendPropertyChanging();
					this._MAGV = value;
					this.SendPropertyChanged("MAGV");
					this.OnMAGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(13)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Int")]
		public System.Nullable<int> MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_GIAOVIEN", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.GIAOVIENs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.GIAOVIENs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOCSINH")]
	public partial class HOCSINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHS;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private System.Nullable<int> _MALOP;
		
		private System.Nullable<int> _ID;
		
		private string _AVATAR;
		
		private EntitySet<DANHGIA> _DANHGIAs;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHSChanging(int value);
    partial void OnMAHSChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnMALOPChanging(System.Nullable<int> value);
    partial void OnMALOPChanged();
    partial void OnIDChanging(System.Nullable<int> value);
    partial void OnIDChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    #endregion
		
		public HOCSINH()
		{
			this._DANHGIAs = new EntitySet<DANHGIA>(new Action<DANHGIA>(this.attach_DANHGIAs), new Action<DANHGIA>(this.detach_DANHGIAs));
			this._LOP = default(EntityRef<LOP>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHS
		{
			get
			{
				return this._MAHS;
			}
			set
			{
				if ((this._MAHS != value))
				{
					this.OnMAHSChanging(value);
					this.SendPropertyChanging();
					this._MAHS = value;
					this.SendPropertyChanged("MAHS");
					this.OnMAHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(200)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="Int")]
		public System.Nullable<int> MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="VarChar(50)")]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOCSINH_DANHGIA", Storage="_DANHGIAs", ThisKey="MAHS", OtherKey="MAHS")]
		public EntitySet<DANHGIA> DANHGIAs
		{
			get
			{
				return this._DANHGIAs;
			}
			set
			{
				this._DANHGIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_HOCSINH", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.HOCSINHs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.HOCSINHs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_HOCSINH", Storage="_TAIKHOAN", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.HOCSINHs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.HOCSINHs.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = this;
		}
		
		private void detach_DANHGIAs(DANHGIA entity)
		{
			this.SendPropertyChanging();
			entity.HOCSINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOAHOC")]
	public partial class KHOAHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKHOAHOC;
		
		private string _TENKHOAHOC;
		
		private string _MOTA;
		
		private System.Nullable<decimal> _HOCPHI;
		
		private string _ANHBIA;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private string _THANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHOAHOCChanging(int value);
    partial void OnMAKHOAHOCChanged();
    partial void OnTENKHOAHOCChanging(string value);
    partial void OnTENKHOAHOCChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnHOCPHIChanging(System.Nullable<decimal> value);
    partial void OnHOCPHIChanged();
    partial void OnANHBIAChanging(string value);
    partial void OnANHBIAChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnTHANHTOANChanging(string value);
    partial void OnTHANHTOANChanged();
    #endregion
		
		public KHOAHOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOAHOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKHOAHOC
		{
			get
			{
				return this._MAKHOAHOC;
			}
			set
			{
				if ((this._MAKHOAHOC != value))
				{
					this.OnMAKHOAHOCChanging(value);
					this.SendPropertyChanging();
					this._MAKHOAHOC = value;
					this.SendPropertyChanged("MAKHOAHOC");
					this.OnMAKHOAHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHOAHOC", DbType="NVarChar(50)")]
		public string TENKHOAHOC
		{
			get
			{
				return this._TENKHOAHOC;
			}
			set
			{
				if ((this._TENKHOAHOC != value))
				{
					this.OnTENKHOAHOCChanging(value);
					this.SendPropertyChanging();
					this._TENKHOAHOC = value;
					this.SendPropertyChanged("TENKHOAHOC");
					this.OnTENKHOAHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCPHI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> HOCPHI
		{
			get
			{
				return this._HOCPHI;
			}
			set
			{
				if ((this._HOCPHI != value))
				{
					this.OnHOCPHIChanging(value);
					this.SendPropertyChanging();
					this._HOCPHI = value;
					this.SendPropertyChanged("HOCPHI");
					this.OnHOCPHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANHBIA", DbType="VarChar(50)")]
		public string ANHBIA
		{
			get
			{
				return this._ANHBIA;
			}
			set
			{
				if ((this._ANHBIA != value))
				{
					this.OnANHBIAChanging(value);
					this.SendPropertyChanging();
					this._ANHBIA = value;
					this.SendPropertyChanged("ANHBIA");
					this.OnANHBIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTOAN", DbType="NVarChar(MAX)")]
		public string THANHTOAN
		{
			get
			{
				return this._THANHTOAN;
			}
			set
			{
				if ((this._THANHTOAN != value))
				{
					this.OnTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._THANHTOAN = value;
					this.SendPropertyChanged("THANHTOAN");
					this.OnTHANHTOANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOP;
		
		private string _TENLOP;
		
		private EntitySet<GIAOVIEN> _GIAOVIENs;
		
		private EntitySet<HOCSINH> _HOCSINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPChanging(int value);
    partial void OnMALOPChanged();
    partial void OnTENLOPChanging(string value);
    partial void OnTENLOPChanged();
    #endregion
		
		public LOP()
		{
			this._GIAOVIENs = new EntitySet<GIAOVIEN>(new Action<GIAOVIEN>(this.attach_GIAOVIENs), new Action<GIAOVIEN>(this.detach_GIAOVIENs));
			this._HOCSINHs = new EntitySet<HOCSINH>(new Action<HOCSINH>(this.attach_HOCSINHs), new Action<HOCSINH>(this.detach_HOCSINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOP", DbType="NChar(10)")]
		public string TENLOP
		{
			get
			{
				return this._TENLOP;
			}
			set
			{
				if ((this._TENLOP != value))
				{
					this.OnTENLOPChanging(value);
					this.SendPropertyChanging();
					this._TENLOP = value;
					this.SendPropertyChanged("TENLOP");
					this.OnTENLOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_GIAOVIEN", Storage="_GIAOVIENs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<GIAOVIEN> GIAOVIENs
		{
			get
			{
				return this._GIAOVIENs;
			}
			set
			{
				this._GIAOVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_HOCSINH", Storage="_HOCSINHs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<HOCSINH> HOCSINHs
		{
			get
			{
				return this._HOCSINHs;
			}
			set
			{
				this._HOCSINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_GIAOVIENs(GIAOVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
		
		private void attach_HOCSINHs(HOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_HOCSINHs(HOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDANGKYHOC")]
	public partial class PHIEUDANGKYHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPHIEU;
		
		private string _HOTENBE;
		
		private string _HOTENCHA;
		
		private string _HOTENME;
		
		private string _NGHECUACHA;
		
		private string _NGHECUAME;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private System.Nullable<System.DateTime> _NAMSINH;
		
		private System.Nullable<int> _MAKHOAHOC;
		
		private string _GIOITINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUChanging(int value);
    partial void OnMAPHIEUChanged();
    partial void OnHOTENBEChanging(string value);
    partial void OnHOTENBEChanged();
    partial void OnHOTENCHAChanging(string value);
    partial void OnHOTENCHAChanged();
    partial void OnHOTENMEChanging(string value);
    partial void OnHOTENMEChanged();
    partial void OnNGHECUACHAChanging(string value);
    partial void OnNGHECUACHAChanged();
    partial void OnNGHECUAMEChanging(string value);
    partial void OnNGHECUAMEChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnNAMSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNAMSINHChanged();
    partial void OnMAKHOAHOCChanging(System.Nullable<int> value);
    partial void OnMAKHOAHOCChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    #endregion
		
		public PHIEUDANGKYHOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPHIEU
		{
			get
			{
				return this._MAPHIEU;
			}
			set
			{
				if ((this._MAPHIEU != value))
				{
					this.OnMAPHIEUChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEU = value;
					this.SendPropertyChanged("MAPHIEU");
					this.OnMAPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENBE", DbType="NVarChar(50)")]
		public string HOTENBE
		{
			get
			{
				return this._HOTENBE;
			}
			set
			{
				if ((this._HOTENBE != value))
				{
					this.OnHOTENBEChanging(value);
					this.SendPropertyChanging();
					this._HOTENBE = value;
					this.SendPropertyChanged("HOTENBE");
					this.OnHOTENBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENCHA", DbType="NVarChar(50)", CanBeNull=false)]
		public string HOTENCHA
		{
			get
			{
				return this._HOTENCHA;
			}
			set
			{
				if ((this._HOTENCHA != value))
				{
					this.OnHOTENCHAChanging(value);
					this.SendPropertyChanging();
					this._HOTENCHA = value;
					this.SendPropertyChanged("HOTENCHA");
					this.OnHOTENCHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENME", DbType="NVarChar(10)", CanBeNull=false)]
		public string HOTENME
		{
			get
			{
				return this._HOTENME;
			}
			set
			{
				if ((this._HOTENME != value))
				{
					this.OnHOTENMEChanging(value);
					this.SendPropertyChanging();
					this._HOTENME = value;
					this.SendPropertyChanged("HOTENME");
					this.OnHOTENMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHECUACHA", DbType="NVarChar(50)")]
		public string NGHECUACHA
		{
			get
			{
				return this._NGHECUACHA;
			}
			set
			{
				if ((this._NGHECUACHA != value))
				{
					this.OnNGHECUACHAChanging(value);
					this.SendPropertyChanging();
					this._NGHECUACHA = value;
					this.SendPropertyChanged("NGHECUACHA");
					this.OnNGHECUACHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHECUAME", DbType="NVarChar(50)")]
		public string NGHECUAME
		{
			get
			{
				return this._NGHECUAME;
			}
			set
			{
				if ((this._NGHECUAME != value))
				{
					this.OnNGHECUAMEChanging(value);
					this.SendPropertyChanging();
					this._NGHECUAME = value;
					this.SendPropertyChanged("NGHECUAME");
					this.OnNGHECUAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(200)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NAMSINH
		{
			get
			{
				return this._NAMSINH;
			}
			set
			{
				if ((this._NAMSINH != value))
				{
					this.OnNAMSINHChanging(value);
					this.SendPropertyChanging();
					this._NAMSINH = value;
					this.SendPropertyChanged("NAMSINH");
					this.OnNAMSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOAHOC", DbType="Int")]
		public System.Nullable<int> MAKHOAHOC
		{
			get
			{
				return this._MAKHOAHOC;
			}
			set
			{
				if ((this._MAKHOAHOC != value))
				{
					this.OnMAKHOAHOCChanging(value);
					this.SendPropertyChanging();
					this._MAKHOAHOC = value;
					this.SendPropertyChanged("MAKHOAHOC");
					this.OnMAKHOAHOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDANGNHAP;
		
		private string _MATKHAU;
		
		private string _HOTEN;
		
		private string _SDT;
		
		private int _ID;
		
		private EntitySet<HOCSINH> _HOCSINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDANGNHAPChanging(string value);
    partial void OnTENDANGNHAPChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._HOCSINHs = new EntitySet<HOCSINH>(new Action<HOCSINH>(this.attach_HOCSINHs), new Action<HOCSINH>(this.detach_HOCSINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="VarChar(50)")]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this.OnTENDANGNHAPChanging(value);
					this.SendPropertyChanging();
					this._TENDANGNHAP = value;
					this.SendPropertyChanged("TENDANGNHAP");
					this.OnTENDANGNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(50)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_HOCSINH", Storage="_HOCSINHs", ThisKey="ID", OtherKey="ID")]
		public EntitySet<HOCSINH> HOCSINHs
		{
			get
			{
				return this._HOCSINHs;
			}
			set
			{
				this._HOCSINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOCSINHs(HOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_HOCSINHs(HOCSINH entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGBAO")]
	public partial class THONGBAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATHONGBAO;
		
		private string _TIEUDE;
		
		private string _NOIDUNG;
		
		private string _HINHANH;
		
		private string _VIDEO;
		
		private System.Nullable<System.DateTime> _NGAYTHONGBAO;
		
		private string _MOTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHONGBAOChanging(int value);
    partial void OnMATHONGBAOChanged();
    partial void OnTIEUDEChanging(string value);
    partial void OnTIEUDEChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnVIDEOChanging(string value);
    partial void OnVIDEOChanged();
    partial void OnNGAYTHONGBAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHONGBAOChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    #endregion
		
		public THONGBAO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHONGBAO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATHONGBAO
		{
			get
			{
				return this._MATHONGBAO;
			}
			set
			{
				if ((this._MATHONGBAO != value))
				{
					this.OnMATHONGBAOChanging(value);
					this.SendPropertyChanging();
					this._MATHONGBAO = value;
					this.SendPropertyChanged("MATHONGBAO");
					this.OnMATHONGBAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TIEUDE
		{
			get
			{
				return this._TIEUDE;
			}
			set
			{
				if ((this._TIEUDE != value))
				{
					this.OnTIEUDEChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE = value;
					this.SendPropertyChanged("TIEUDE");
					this.OnTIEUDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="VarChar(30)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIDEO", DbType="NVarChar(30)")]
		public string VIDEO
		{
			get
			{
				return this._VIDEO;
			}
			set
			{
				if ((this._VIDEO != value))
				{
					this.OnVIDEOChanging(value);
					this.SendPropertyChanging();
					this._VIDEO = value;
					this.SendPropertyChanged("VIDEO");
					this.OnVIDEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHONGBAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYTHONGBAO
		{
			get
			{
				return this._NGAYTHONGBAO;
			}
			set
			{
				if ((this._NGAYTHONGBAO != value))
				{
					this.OnNGAYTHONGBAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHONGBAO = value;
					this.SendPropertyChanged("NGAYTHONGBAO");
					this.OnNGAYTHONGBAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINHOATDONG")]
	public partial class THONGTINHOATDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHOATDONG;
		
		private string _TENHOATDONG;
		
		private string _DIADIEM;
		
		private string _NOIDUNG;
		
		private string _TENGV;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<decimal> _PHITHAMGIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHOATDONGChanging(int value);
    partial void OnMAHOATDONGChanged();
    partial void OnTENHOATDONGChanging(string value);
    partial void OnTENHOATDONGChanged();
    partial void OnDIADIEMChanging(string value);
    partial void OnDIADIEMChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnTENGVChanging(string value);
    partial void OnTENGVChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnPHITHAMGIAChanging(System.Nullable<decimal> value);
    partial void OnPHITHAMGIAChanged();
    #endregion
		
		public THONGTINHOATDONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHOATDONG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHOATDONG
		{
			get
			{
				return this._MAHOATDONG;
			}
			set
			{
				if ((this._MAHOATDONG != value))
				{
					this.OnMAHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._MAHOATDONG = value;
					this.SendPropertyChanged("MAHOATDONG");
					this.OnMAHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHOATDONG", DbType="NVarChar(50)")]
		public string TENHOATDONG
		{
			get
			{
				return this._TENHOATDONG;
			}
			set
			{
				if ((this._TENHOATDONG != value))
				{
					this.OnTENHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._TENHOATDONG = value;
					this.SendPropertyChanged("TENHOATDONG");
					this.OnTENHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEM", DbType="NVarChar(100)")]
		public string DIADIEM
		{
			get
			{
				return this._DIADIEM;
			}
			set
			{
				if ((this._DIADIEM != value))
				{
					this.OnDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._DIADIEM = value;
					this.SendPropertyChanged("DIADIEM");
					this.OnDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENGV", DbType="NVarChar(50)")]
		public string TENGV
		{
			get
			{
				return this._TENGV;
			}
			set
			{
				if ((this._TENGV != value))
				{
					this.OnTENGVChanging(value);
					this.SendPropertyChanging();
					this._TENGV = value;
					this.SendPropertyChanged("TENGV");
					this.OnTENGVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHITHAMGIA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHITHAMGIA
		{
			get
			{
				return this._PHITHAMGIA;
			}
			set
			{
				if ((this._PHITHAMGIA != value))
				{
					this.OnPHITHAMGIAChanging(value);
					this.SendPropertyChanging();
					this._PHITHAMGIA = value;
					this.SendPropertyChanged("PHITHAMGIA");
					this.OnPHITHAMGIAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
